blog/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
 path('admin/', admin.site.urls),
 path('', include('blogger.urls', namespace='blogger')),
]

blogger/urls.py
from django.urls import path
from . import views



app_name = 'blogger'
urlpatterns = [
path('', views.post_list, name='post_list'),

path('blogger-list/', views.PostListView.as_view()),

path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),

path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail'),
]

blogger/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_post', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    tags = TaggableManager()  #Теги

    class Meta:
        ordering = ('-publish',)    

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blogger:post_detail', args=[self.publish.year,self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(null=True, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blogger/forms.py
from django import forms 

from .models import Comment 

class CommentForm(forms.ModelForm):
     
     class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blogger/views.py
from django.shortcuts import render, get_object_or_404 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import CommentForm
from taggit.models import Tag
# Create your views here.

class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'list.html'

def post_list(request, tag_slug=None):
    object_list = Post.objects.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 1)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'list.html', {'page': page, 'posts': posts})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,publish__year=year,publish__month=month,publish__day=day)
    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
    # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,'detail.html',{'post': post,
                                         'comments': comments,
                                         'new_comment': new_comment,
                                         'comment_form': comment_form}
)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
 <div id="content">
 {% block content %}{% endblock %}
 </div>
 <div id="sidebar">
 <h2>My blog</h2>
 <p>This is my blog.</p>
 </div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

 <h1>{{ post.title }}</h1>
 <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
 {{ post.body|linebreaks }}



{% if new_comment %}
 <h2>Your comment has been added.</h2>
{% else %}
 <h2>Add a new comment</h2>
 <form action="." method="post">
 {{ comment_form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Add comment"></p>
 </form>
{% endif %}



{% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}


    
{% for comment in comments %}
 <div class="comment">
 <p class="info">
 Comment {{ forloop.counter }} by {{ comment.name }}
 {{ comment.created }}
 </p>
 {{ comment.body|linebreaks }}
 </div>
{% empty %}
 <p>There are no comments yet.</p>
{% endfor %}

{% endblock %}

templates/list.html
{% extends "base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
 <h1>My Blog</h1>

{% if tag %}
    <h2>Posts tagget with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
 <h2>
 <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
 </h2>

 <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
 Tags:
 {% for tag in post.tags.all %}
 <a href="{% url "blogger:post_list_by_tag" tag.slug %}">
 {{ tag.name }}
 </a>
 {% if not forloop.last %}, {% endif %}
 {% endfor %}

 <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
 {{ post.body|truncatewords:30|linebreaks }}
 {% endfor %}
 {% include "pagination.html" with page=posts %}
 {% endblock %}
 

templates/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">Previous</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
   </div>